### ISSUE TITLE
[Bug] minSDKVersion

### ISSUE THREAD

**Issue by mooomooo** [yourealwaysbe/forkyz#11]
`setAutoSizeTextTypeUniformWithConfiguration` (in NotesActivity and PlayActivity) was only added in API 26, so you'd need to add guards around it to prevent errors when running this on lower APIs.  Alternately, you'd need to adjust `android:minSdkVersion` accordingly in `AndroidManifest.xml`, which would prevent this app from even installing on anyone with a lower API.

See commits: 3ab5a51, 5723335

**Comment by matthewhague** [comment]
Thanks -- hopefully fixed it.
