### ISSUE TITLE
Missing class - StoragePermissionDialog

### ISSUE THREAD

**Issue by simonpoole1** [yourealwaysbe/forkyz#15]
Hi - I think you've forgotten to commit `app.crossword.yourealwaysbe.view.StoragePermissionDialog`

**Comment by yourealwaysbe** [comment]
Oops, sorry. Should be fixed now.

I've also push a big change, replacing java.util.Date with java.time.LocalDate. I may have introduced a few bugs with the downloaders, but it seems to work ok with the ones i use. The others have been unmaintained for years, so i don't know what testing will find :) If you spot any issues let me know.
