### ISSUE TITLE
keyboard vanishes

### ISSUE THREAD

**Issue by mcaphasia** [yourealwaysbe/forkyz#25]
Keyboard disappears when I manually select an empty space to input an answer. Reappears when I tap the space to change direction. This happens about 90% of the time. It doesn't happen when using the arrow keys to move, or solving a clue. Using Android 11 on a pixel 3a.

**Comment by yourealwaysbe** [comment]
I expect this is the intended behaviour. When you select a new clue the keyboard should hide. When you click a selected clue, it shows again. I dunno, it suits me -- keeps the keyboard out of the way while i'm browsing the board looking for clues i can solve :)

You can change it in the settings.  Look for "Interaction Settings" and "Show/Hide In-App Keyboard".

Let me know if this is not what you were after.

**Comment by mcaphasia** [comment]
Odd, I would never have guessed that was intentional. The board never changes so it didn't make sense to me. Ah well. Thank you! Love the app.

**Comment by yourealwaysbe** [comment]
The keyboard should only hide when the selected clue changes. Let me know if something other than that is happening.

I guess a fourth keyboard mode between "always show" and "show sparingly" should be something like "hide with back button" (and reappear on clicking a selected clue). Will consider that for the next version.
