### ISSUE TITLE
Delete incorrect letters

### ISSUE THREAD

**Issue by sttrebo** [yourealwaysbe/forkyz#27]
When I am typing letters, incorrect ones are highlighted (correctly) but when I try and backspace or delete the incorrect letters, nothing happens.  It's odd that sometimes it works fine, others it doesn't and I have yet to find out the exact circumstances when it works properly.

**Comment by yourealwaysbe** [comment]
Thanks for the report.

What are your settings for "don't delete crossing words" and "preserve correct boxes when show errors"?

If "don't delete crossing words" is set, delete will not do anything if the letter also belongs to another clue that has a solution entered. This can end up seeming a bit odd sometimes. I think it should be off by default.

Does the bad behaviour disappear when show errors is turned off?

**Comment by yourealwaysbe** [comment]
Another thought: when delete doesn't do anything, what happens if you leave the puzzle and reenter? It might be that the display is not being refreshed properly.

**Comment by sttrebo** [comment]
Hi, sorry it took so long to respond.  The leave puzzle and reenter didn't change anything.  But the 'don't delete crossing words' did the trick when I unchecked it.  It almost seemed random,  but I haven't been paying enough attention to the details to see if I can document the exact sequence.  Sorry, but I'll try and pay more attention.

**Comment by matthewhague** [comment]
Cool -- the don't delete crossing behaviour isn't really obvious unless you know what's going on. I thought i'd turned it off by default, but realised that the code assumes it's on by default. I'll fix that for the next release.
