### ISSUE TITLE
Optional progress measure of number of filled boxes or correctly filled boxes?

### ISSUE THREAD

**Issue by Dogora** [yourealwaysbe/forkyz#28]
Thank you for the update to Shortyz!

Can you please make the box count an option between filled or correct? That leaves it up to the user if he/she wants to cheat.

**Comment by yourealwaysbe** [comment]
Hah :)

What about the "show errors" option?

**Comment by Dogora** [comment]
The "show errors" option shows all errors for the whole grid, even those that I will fix as I solve the puzzle. The box count "cheat" can help with a particularly difficult word without giving away all the errors.

**Comment by yourealwaysbe** [comment]
Aha, i see -- kind of a "show errors under cursor" option. At the moment you can reveal the current letter, but this is a bit too much. Certainly something i can add when i have the time to work on it.

**Comment by yourealwaysbe** [comment]
I've implemented a "show errors under cursor" option. It is currently on the version10 branch and relatively untested.

**Comment by yourealwaysbe** [comment]
Version 10 should be on its way to F-Droid. I'll close this issue for now.
