### ISSUE TITLE
Please support alternative keyboard layouts: Dvorak, etc.

### ISSUE THREAD

**Issue by maniaphobic** [yourealwaysbe/forkyz#33]
Hi,

Great work on Forkyz!

I use the Dvorak keyboard layout and haven't found a way to switch the layout of the app's QWERTY keyboard. I'd be grateful if you could add support for alternate layouts. Perhaps this could extend the work you did for [issue #30](https://github.com/yourealwaysbe/forkyz/issues/30)?

Thank you!

**Comment by yourealwaysbe** [comment]
Thanks for the request. Currently there is no way to change layout, which is one annoying side effect of not being able to use Android system keyboards reliably.

In principle, alternative layouts using A-Z characters are quite easy -- we'd just need to create an alternative [forkyz_keyboard.xml](https://github.com/yourealwaysbe/forkyz/blob/master/app/src/main/res/layout/forkyz_keyboard.xml) layout. Then add some config parameters to ForkyzKeyboard.java, probably pulled out of the shared preferences in the KeyboardManager.java and set via the normal preferences.xml file.

I'm entering a surge period at work though, so might not get around to it for a while. I'm happy to accept pull requests of course :)

**Comment by yourealwaysbe** [comment]
The WIP version13 branch now supports QWERTY, QWERTZ, Dvorak, and Colemak. Are there any others i should cover?

**Comment by maniaphobic** [comment]
Excellent, thank you! I only need Dvorak, but I'll defer to others to suggest additional layouts.
