### ISSUE TITLE
Guardian Daily Cryptic [App Crash]

### ISSUE THREAD

**Issue by dtoxic47** [yourealwaysbe/forkyz#37]
On Samsung S10+ A11 OneUI 3 the "Guardian Daily Cryptic" downloads fine but when entering the puzzle the app Crashes

let me know if you need more info

**Comment by yourealwaysbe** [comment]
Confirmed here. Looks like a daft null pointer error, sorry about that. I will fix today or tomorrow. I think the error is triggered by the puzzle shape, so the current version will hopefully still work on some days (it was for me).

**Comment by dtoxic47** [comment]
Awesome,thx
