### ISSUE TITLE
App Crash [Folders issue]

### ISSUE THREAD

**Issue by dtoxic47** [yourealwaysbe/forkyz#38]
Found an interesting error
So please do try it and let me know if you experience the same issue

Installed the app and downloaded some puzzles, before downloading any puzzles i changed the storage location to External Storage(still on the phone no SDcard)\Documents\Crosswords\ (inside the Crossword Folder there are two additional folders witch are empty (Archive and Temp) witch are created after downloading puzzles, everything is working excellent until you by accident or some cleaning app (in my case SD Maid) delete those two empty folders (archive and temp),note that the folders where empty so the cleaning app considers them obsolete and not needed, what remains are the puzzle files inside the Crossword folder (in documents folder witch i created and selected trough settings) if all that happens the app crashes and wont start,so to fix this either clear data of the app or revoke storage permission to use that folder delete everything inside it and download the puzzles again,i can reproduce this error always.

anyway just pointing it out if someone else stumbles upon this issue,for now i excluded the folder from the cleaning app and no more problems.

Let me know if i can help further.

**Comment by matthewhague** [comment]
I added a fix for this, though i'm not sure if you'll like it. The basic error was a directory existence check that would fail if the directory doesn't exist! I fixed that, i think..

The app creates the folders in advance though, so your cleaner will delete them, then Forkyz will put them right back. In theory the code can be reorganised to create the internal folders as/when needed, but i think that's not urgent for now.

The version17 branch has the fixes so far.

**Comment by yourealwaysbe** [comment]
Minor improvement: i've removed the temp directory, it had become redundant.

**Comment by dtoxic47** [comment]
> I added a fix for this, though i'm not sure if you'll like it. The basic error was a directory existence check that would fail if the directory doesn't exist! I fixed that, i think..
> 
> The app creates the folders in advance though, so your cleaner will delete them, then Forkyz will put them right back. In theory the code can be reorganised to create the internal folders as/when needed, but i think that's not urgent for now.
> 
> The version17 branch has the fixes so far.

better remove it then so that there are no problems, cleaning app or not :) thx for looking into this
