### ISSUE TITLE
Newsday 2022-03-03 crashes Forkyz

### ISSUE THREAD

**Issue by gkuenning** [yourealwaysbe/forkyz#39]
The Newsday puzzle for March 3, 2022 crashes Forkyz when it's opened.  I tried to figure out why by fiddling with the .puz file, but everything looks kosher to me and I'm not in a position to run Forkyz in a debugger.

**Comment by dtoxic47** [comment]
Can confirm crashes on my phone also S10+ A11

Also Independent Daily Cryptic is crashing March 6

**Comment by yourealwaysbe** [comment]
Thanks for the report.

I think this is the same as #37 and is fixed in version 17 (tested, works for me). Please reopen if it doesn't work for you on version 17 (should be on FDroid soon).
