### ISSUE TITLE
[Feature Request] Scheduled Check/Download

### ISSUE THREAD

**Issue by dtoxic47** [yourealwaysbe/forkyz#41]
Hi,i don't know if this is in the scope of the app or will it require major code edit (not a coder just trowing some ideas at you),but would it be possible to add a scheduled check say to pick our own time to download puzzles in the background,example: 7am Monday trough Sunday or just if we want 7am and a specific day and ignore all others.

Hope it's not a tall order

**Comment by yourealwaysbe** [comment]
In principle it just means getting the right parameters to [this line](https://github.com/yourealwaysbe/forkyz/blob/7c3b3d945ae2c3809aa2153b22b73df04b933de9/app/src/main/java/app/crossword/yourealwaysbe/service/BackgroundDownloadService.java#L43) of code, which currently looks like it runs every hour.

Some settings and a dialog are certainly doable, but it's something i might not get around to right away.

**Comment by dtoxic47** [comment]
Nobody said right away :) but if it is doable please do consider adding such a feature down the line,my reasoning is why have it check  every hour and waste battery when it can do it once a day or once a week,anyway thx for looking into this.

**Comment by yourealwaysbe** [comment]
I think this is now working in version21 (on FDroid now). I'll close this.

**Comment by dtoxic47** [comment]
thx
