### ISSUE TITLE
"Skip filled boxes" doesn't always skip filled boxes

### ISSUE THREAD

**Issue by ieure** [yourealwaysbe/forkyz#44]
[Screen recording illustrating the problem](
https://user-images.githubusercontent.com/35252/164288301-0397f3dc-d253-4b06-a1a2-dba28e619927.mp4)

With any box on the third-from-the-bottom line (starting with the "S" in "PLASMA"), tapping the next clue in the same direction button highlights the box filled with "M."  Since I've selected "skip filled boxes," it should select the empty box next to the M.  Similarly, when tapping next clue in same direction from there, it selects the "A" instead of the empty box next to it.

This is a regression vs. Shortyz.  It doesn't *always* happen, but happens often enough to be annoying.  It might be related to moving to a clue on a different row/column of the grid.

**Comment by yourealwaysbe** [comment]
Thanks. Pushed a fix to the version20 branch.

I don't make very sophisticated use of the navigation keys, so let me know other oddities you find.
