### ISSUE TITLE
Grid Squares

### ISSUE THREAD

**Issue by claudiacoots** [yourealwaysbe/forkyz#47]
I am having trouble when there is an error for the letter to highlight blue, but when I finally get the answer right, the square stays red. I am wanting to not have it red when I finally get the letter right, is there a way we can make it a setting or fix it?

**Comment by yourealwaysbe** [comment]
There's a "no hint highlighting" option in the display settings. I just checked and it works for me.

Is this option ticked? If so, you might have to close and reopen the puzzle (or force redraw in another way) for it to take effect.

**Comment by yourealwaysbe** [comment]
I'll close this for now on the assumption the "no hint highlighting" option was what you needed. Please reopen if needed.
