### ISSUE TITLE
[Feature request] Custom .puz sources

### ISSUE THREAD

**Issue by mooomooo** [yourealwaysbe/forkyz#5]
Would it be possible to create a new CustomDownloader to allow arbitrary puzzle downloads, using settings options for e.g. a datestring-formatted URL (https://man7.org/linux/man-pages/man1/date.1.html) and update frequency?

P.S.  This fork has been an amazing improvement, thank you for creating it!  I've been using it since the rebrand over a year ago, and I just noticed that you're still developing it.  Forgive me if I'm being selfish, but I've come up with a few feature requests that I'll note in the issues here -- I feel that these enhancements would make this app even better, if you think they'd be worth working on.

**Comment by yourealwaysbe** [comment]
I don't really get much time to implement things unless i'm really motivated, so i probably won't get around to this myself anytime soon. Pull requests welcome :) 

From a backend perspective it's not difficult -- though could be cleaner. Essentially, the `AbstractDownloader` class would need a small implementing class that supplies the configured URLs.

The the UI needs implementing, which is always a faff on Android.

Relevant code parts are below. There's too much hard-coding of available downloaders going on, and this would be a good time to fix that.

* Preference entries are found in `app/src/main/res/preferenes_<mode>.xml`, where `<mode>` is daily, weekly, etc.
* `app/src/main/java/app/crossword/yourealwaysbe/net/Downloaders.java` has a method `getDownloadersFromPrefs` to pick out the chosen downloaders.
* `app/src/main/java/app/crossword/yourealwaysbe/net/AbstractDownloader.java` provides a base class for puzzle download that only needs URL construction implemented (base URL plus puzzle name suffix).

**Comment by yourealwaysbe** [comment]
This is now supported in version13 (thanks for the pull request). (23b51da)

Future development of the feature would be great (not just .puz, more than one source, specify days available), but for now i'll close the issue and leave the rest to natural development.
