### ISSUE TITLE
[feature request] copy text of clue

### ISSUE THREAD

**Issue by pseudomonas** [yourealwaysbe/forkyz#51]
I'd love a way to copy the  text of clues to clipboard so I can share good examples with my friends. At the moment I tend to retype or screenshot depending on how lazy I feel. 

(presumably the easiest interface is getting a pop-up to do so by long-pressing the text of the clue in the notes view, since that action is currently unassigned; but I don't care if it's instead added to one of the menus or whatever.)

**Comment by yourealwaysbe** [comment]
This is a nice idea and shouldn't be too hard to add in. I'll play around with adding a "share clue" option.

**Comment by yourealwaysbe** [comment]
I've implemented this as a "share clue" feature. This just sends the text out to the Android system as a whole, to be picked up by any app that takes text. Messaging or email are typical examples. If you have some sort of clipboard app installed, this will allow copy to clipboard as well. I have one by default on LineageOS 19 (Android 12), but don't appear to have one on LineageOS 14 (Android 7).

It looks like this. Happy to adjust the text a bit.

[
![share-clue](https://user-images.githubusercontent.com/372397/172129716-c9a8ddb9-5813-40cb-837a-d72a0f2ec3fc.png)
](url)

**Comment by pseudomonas** [comment]
I have a (thirdparty, from F-droid) share-to-clipboard app, so I'm set. I
think the way you've chosen is the android-idiomatic way to do it, and
probably the way that will be useful for most "normal users".

I was thinking, I don't know whether I prefer the plain text of the clue or
a "${CLUE}\n ${SETTER} ${DATE} ${URL}" formatted string that automatically
credits the crossword's author. Pretty sure either will be just fine though.

Really feeling like I ought to learn Java again so I can help with all
these feature requests I keep making.

**Comment by yourealwaysbe** [comment]
Cool. I've gone with two versions of the option with setter credit -- i like to include the attribution if i can.

One version includes the board entries (c?s??) the other doesn't.

There's no URL because there isn't really a good one to use stored with the puzzles. The current URLs available in the app are the backend sources (can be quite obtuse) or something like the subscription page for the newspaper (not quite what was intended).

It's via a drop down menu. I'll add options to share the puzzles themselves too :)

**Comment by pseudomonas** [comment]
It seems nice to include attribution, especially since I'm generally sharing clues that I find particularly clever or amusing!

6 Jun 2022 20:44:19 yourealwaysbe ***@***.***>:
