### ISSUE TITLE
Reveal Errors now reveals all tiles

### ISSUE THREAD

**Issue by evilscarp** [yourealwaysbe/forkyz#53]
New behavior between the current version 24 and version 19(??) wherein Menu -> Reveal -> Errors  (and in fact Menu -> Reveal -> Puzzle) reveals all tiles colored as hints, where v19 only revealed crossed tiles with incorrect letters as hints. 

Pleaae revert to v19's behavior?

LineageOS 19.1 (Android 12), Oneplus 5T. 

F-droid store, v24, upgrading from v19

**Comment by yourealwaysbe** [comment]
Thanks for the report, i can take a look.

Could i ask what you mean by "(all?) tiles colored" and "crossed tiles"?

**Comment by evilscarp** [comment]
Apologies, I seem to have used "all" and "crosed" to mean the same thing. When revealing errors, any filled in tile gets colored as a hinted tile whether correct or incorrect, where the old behavior was only to color errored tiles as hinted.

Likewise, reveal Puzzle used to color only incorrectly filled and empty tiles as hinted, where now it reveals all tiles as hinted.

**Comment by yourealwaysbe** [comment]
Aha. Confirmed here too. I'll change it back for the next version. It wasn't intentional.

**Comment by yourealwaysbe** [comment]
Should be fixed for the next version (25).

I'd changed the backend so you can put more than just a single character in a box. This meant the way it checks if the solution and user response had to be updated throughout. I missed updating the checks for the reveal functions, making it think the user got everything wrong.
