### ISSUE TITLE
V25 download problems

### ISSUE THREAD

**Issue by dtoxic47** [yourealwaysbe/forkyz#54]
Ok,so i updated to v25,when there are no crosswords i hit the download button they download but the list is not auto populated, you have to exit the app and re-enter to see the list,also first time 10 crosswords where downloaded,i deleted them and tried again (was testing the list thing) then only 7 where downloaded,and now after 3rd or 4th try i see only 3 crosswords. Could you chek this out before i try to reinstall the app and see if that fixes it,so we can confirm if its apps problem or mine.

P.S the Jonesin Crosswords gets stuck offten just says ...Downloading... and never finishes

P.S2. Ok so this is happening only for today's date if i download crosswords from yesterday everything is ok

**Comment by yourealwaysbe** [comment]
I thought a network issue might be the problem. Possibly either Jonesin is having an off-day, or i'll need to update the download source.

It only refreshes the puzzle list once all downloads finish or fail (unless you force it to refresh some other how, by restarting for example). I suspect it also does all downloads in one background thread, so one hang can block the rest. Perhaps forcing a timeout is needed here (if it's not done by default) (and/or parallel downloads).

Thanks for the report.

**Comment by dtoxic47** [comment]
You might be right,i was doing some testing and it looks like it always hangs on Jonesin so you might be right on that.
You should add a timeout for these kinds of situations like you said or make it so it retries 2-3 times and if it fails move to other sources. was going crazy here for minute thinking my phone started acting up for some reason :)

**Comment by yourealwaysbe** [comment]
The Jonesin (and Wall Street Journal) sources will be down until the end of July. Forkyz uses the same source as Crossword Links and Crossword Field for these. [They know more than i do :)](https://crosswordlinks.substack.com/p/thursday-21-july-2022)

**Comment by dtoxic47** [comment]
thx for the info,hope you can add a timeout feature with ease so we can avoid getting stuck at download.

PS> maybe also add some kind of info at the end of all the downloads so we know witch puzzles got timed out/rejected...just a thought

**Comment by yourealwaysbe** [comment]
The timeout is now a configurable option in Version 26, which should be on its way to FDroid (default 30s timeout).

I didn't see your PS, so there's no notification on failure. That should be easy to add for Version 27.

**Comment by dtoxic47** [comment]
Cool,thx for your time keep up the good work

**Comment by yourealwaysbe** [comment]
Ok, should all be good now. Version 27 should be picked up by FDroid whenever. I'll close this issue. Thanks for the report and suggestions.
