### ISSUE TITLE
[feature request] several sources

### ISSUE THREAD

**Issue by ChainChomsky** [yourealwaysbe/forkyz#55]
currently Universal Crossword fails to download. it does work with a custom source at 'https://herbach.dnsalias.com/uc/uc'yyMMdd'.puz'

also, the wall street journal now releases crosswords daily (not just friday and saturday), which can be found at 'https://herbach.dnsalias.com/wsj/wsj'yyMMdd'.puz'

the washington post magazines's sunday puzzle is available at 'https://herbach.dnsalias.com/Wapo/wp'yyMMdd'.puz'

shout outs to martin herbach. doing the lords work.

**Comment by dtoxic47** [comment]
Here are some crosswords,but i don't know how would one go about importing these into the app,maybe someones knows 

https://www.theepochtimes.com/c-epoch-crosswords

**Comment by yourealwaysbe** [comment]
Thanks for the updates, i'll add them to the next version.

> Here are some crosswords,but i don't know how would one go about importing these into the app,maybe someones knows

Those ones are provided by AmuseLabs. I slowly removed the previous AmuseLabs downloaders as they added a session key for some, and then started obfuscating the data for all. It's not too hard to work around these, but i felt a bit uncomfortable providing the downloads when it seemed like they were making efforts to prevent it.

**Comment by yourealwaysbe** [comment]
I've added the WSJ daily and WaPo Sunday.

Universal is working ok for me at the moment. Let me know if you're still having trouble.

**Comment by ruralTom** [comment]
I realize this is closed but I didn't want to make a new issue to ask a question. Why do some of these fail to download? It seems intermittent, because one day I'll be fine and the next it won't.

Curious if it's something I'm doing or a quirk or the actual sources..

**Comment by yourealwaysbe** [comment]
I don't know of any particular reason. The only thing that i can think of is that some puzzles aren't available immediately on the day of release. E.g. if i try to download a puzzle at 1am it will fail because the day's puzzle isn't online yet.

Which sources in particular do you have trouble with? And how frequent are the download problems?

**Comment by ruralTom** [comment]
It kinda varies. I'll pay more attention and stick to being a day behind publication and see if it helps.

Sep 13, 2022 2:30:24 AM yourealwaysbe ***@***.***>:

**Comment by yourealwaysbe** [comment]
> It kinda varies. I'll pay more attention and stick to being a day behind publication and see if it helps.

Might this issue be related to #58?
