### ISSUE TITLE
Consistent download failure notifications

### ISSUE THREAD

**Issue by clockwinder** [yourealwaysbe/forkyz#58]
Every day I get notifications that "Puzzle Downloads Failed", even though I can see and play the puzzles that it is saying the download has failed on.  Beyond that, if I close the failure notification, within a few hours I will get the download failure message again. 
 
Please let me know what other info I can provide.

<details>
  <summary>Click me for pictures</summary>

Clearly the puzzles are there.
![image](https://user-images.githubusercontent.com/54368516/193859676-9c64502b-f9be-4eee-87c2-d98ad0fe7503.png)

Error notifications
![image](https://user-images.githubusercontent.com/54368516/193859733-8a8422a9-0e40-4d44-8854-34127fc612df.png)

~55 notifications a day from this app alone
![image](https://user-images.githubusercontent.com/54368516/193861968-5a871e2a-7608-41a2-b58c-098abc95e1e2.png)
</details>

**Comment by yourealwaysbe** [comment]
Hmm, that's weird. Thanks for the report.

Did it just start happening after an upgrade? Which version are you using?

Is automatic download enabled in the settings? Had you enabled it in the past? What background download options are set?

Does the failure notification only appear when your phone is closed?

**Comment by clockwinder** [comment]
I'm sorry I can't specify when it started happening, at least a month ago.  I was busy and it was easy to ignore until I had time to report.  Fdroid says I'm on V29.

Automatic download is on.  It has always been enabled.  For a period of time the downloads were failing but that was resolved with an update.  Download hourly is on, no days are set, daily time is 08:00, wifi only, no roaming, not chile charging only.

When you specify "closed" you mean locked? If that's the case, then No.  I got the error again while I was looking in the settings to respond to your questions.

**Comment by yourealwaysbe** [comment]
Thanks. I've managed to reproduce it on my end, and at the same time download the same puzzle twice.

My guess is that the logic is broken for reporting failures, and it's confusing skipped downloads of existing files with failures. I'll look into that when i can.

**Comment by clockwinder** [comment]
Great!  Glad to know my lack of concise information didn't hinder the process too much.  Always here if you have more questions.
