### ISSUE TITLE
Themes Suggestions

### ISSUE THREAD

**Issue by dtoxic47** [yourealwaysbe/forkyz#60]
Where could i download V31? i don't like the new theme but also i experience some download errors on various puzzles,V31 was the most stable for my phone so far

**Comment by yourealwaysbe** [comment]
If you're happy to build it yourself, you can checkout and compile the [version31 branch](https://github.com/yourealwaysbe/forkyz/tree/version31).

Otherwise, i any other release infrastructure set up, but attached is my own build. It's signed by a different key to the FDroid version (signed with FDroid's secret keys), so you'll have to do a full uninstall/reinstall.

What download errors are you getting? It would be good to get them fixed.

[forkyz.apk.zip](https://github.com/yourealwaysbe/forkyz/files/10068402/forkyz.apk.zip)

**Comment by dtoxic47** [comment]
Hi i tried building it but i get 1 error when compiling with installed JDK (latest version) unfortunately my coding and troubleshooting skills when it comes to java and coding in general are on par with my Chinese speaking skills meaning zero

The failed downloads are USA today,Universal Crosswords and a notification "Some puzzles downloaded and some failed" witch i assume is the summary

**Comment by yourealwaysbe** [comment]
>i get 1 error when compiling with installed JDK (latest version)

Hopefully the apk above is enough. You'll need Java 11 to compile (i don't think Android works with later versions).

> The failed downloads are USA today,Universal Crosswords and a notification "Some puzzles downloaded and some failed" witch i assume is the summary

Thanks. Confirmed on my end. Sometimes timezones can cause issues in that, if you're ahead, you're trying to download the puzzle before it's available. That part of the UI could be cleaner. However, i also can't download yesterday's puzzles. I'll look into it when i can.

**Comment by dtoxic47** [comment]
Yeah me also on yesterdays puzzles also fail,as for the theme i would suggest if it's not too much of a work to implement a theme selector? Legacy (as in V31) and New Theme Style,settings layout could remain the same as they look cleaner in the later version,easier to find what one is looking for

**Comment by zythra** [comment]
Came by to log an issue with the downloads, but since it's already here I'll confirm that I'm also no longer able to download USA Today and Universal Crosswords with the latest version.  I don't believe it's a timezone issue as I can no longer download either of those regardless of time of day.

**Comment by yourealwaysbe** [comment]
> i would suggest if it's not too much of a work to implement a theme selector?

I don't know tbh -- i'd have to look into Android support for theme selection (and see what happens if i dump the old theme files into the new code).

It also depends what you're hoping for. If it's just a case of turning the action bar blue again, that might be straightforward.

**Comment by yourealwaysbe** [comment]
I'm going to split this into two issues. This one can be for themes. I'll make a new one for the downloads problem.

**Comment by dtoxic47** [comment]
i renamed the issue to avoid confusion

**Comment by yourealwaysbe** [comment]
I added a legacy-like theme option for Version 35.

It's not an exact replica of the old theme, so let me know if i missed something that's important to you.

**Comment by dtoxic47** [comment]
Awesome,will let you know when it drops on F-Droid

**Comment by yourealwaysbe** [comment]
I'll give it a couple of days before releasing Version 35 (in case any bugs come up). Then it'll take maybe up to a week for FDroid to catch it.

**Comment by dtoxic47** [comment]
No problem,thx for taking the time to look into this,as to theme the only thing that i did not like is the "pill"shaped selection because it looks kinda off on a curved screen phone at least to me

**Comment by yourealwaysbe** [comment]
> the only thing that i did not like is the "pill"shaped selection

I wanted some kind of identification of the selected items that didn't rely only on the background colour -- iirc, sometimes the dynamic theme can pick background colours that are hard to distinguish. I'm fairly indifferent about the mechanism.

Would borders work better?

<img alt="The browse puzzles screen with selections shown by primary color borders" src="https://user-images.githubusercontent.com/372397/204828703-c9b8d27a-ebe5-4885-9cdd-22ed3c1ad3e1.png" width=200/>

**Comment by dtoxic47** [comment]
Yeah,that looks good,i assume same will be in the dark theme

**Comment by yourealwaysbe** [comment]
> Yeah,that looks good,i assume same will be in the dark theme

Yep, but orange :)
