### ISSUE TITLE
Universal/USA Today/WSJ Downloads Failing

### ISSUE THREAD

**Issue by yourealwaysbe** [yourealwaysbe/forkyz#61]
Split out from #60.

**Comment by th0mcat** [comment]
USAToday was having issues with their crossword globally over the last 4 days.  Some people say it's back, but the link Forkyz (and my script) used to pull it is generating a 503.   

http://picayune.uclick.com/comics/usaon/data/usaon221122-data.xml

I wonder if USAToday is pulling the plug on their free crosswords.

**Comment by yourealwaysbe** [comment]
They are both working for me this morning.

@th0mcat is it still 503ing for you? Which country are you accessing them from (perhaps there's some kind of filter)?

@dtoxic47 does it work on your end now?

**Comment by dtoxic47** [comment]
Only wall street journal failed today (previous days work) all others work

**Comment by th0mcat** [comment]
Can confirm it's working again

**Comment by yourealwaysbe** [comment]
> Only wall street journal failed today (previous days work) all others work

Bah -- previous days aren't working for me for the WSJ. I'll keep an eye on it.

edit: oh, because i hadn't turned the internet on, d'oh.. no WSJ for today, but it might be a bit early. I'll add "no internet warning" and "timezone sensitive downloads" to the wishlist.

**Comment by yourealwaysbe** [comment]
WSJ was working for me today this morning. I'll close this issue now.

Broken downloader notifications always welcome!
