### ISSUE TITLE
Failed Download

### ISSUE THREAD

**Issue by dtoxic47** [yourealwaysbe/forkyz#63]
On the latest v35 version Sheffer and Thomas joseph crosswords fail to download for the previous day (Monday),could you check if it's on their end?

**Comment by yourealwaysbe** [comment]
Bargh, sorry, completely my fault. I mixed up a couple of arguments when doing #62 and didn't notice the King Digital sources weren't downloading.

Should be fixed now, Version 36 on its way to FDroid.
