### ISSUE TITLE
Add sources

### ISSUE THREAD

**Issue by ojppe** [yourealwaysbe/forkyz#64]
**To download puzzles:** (are these possible?)

Dutch
https://www.telegraaf.nl/puzzels/kruiswoord

Flemish
https://www.standaard.be/kruiswoordraadsel

**To online sources:**

Crosshare
https://crosshare.org/

**Comment by yourealwaysbe** [comment]
Thanks.

I'll add the online source.

For the downloader sources, they'll require more work. One looks more straightforward than the other. I'm currently working on acrostic support, but will have a go eventually.

**Comment by yourealwaysbe** [comment]
These should be on their way to FDroid now in Version 38. Let me know if there are any issues. Thanks.

**Comment by ojppe** [comment]
You're amazing. Works great so far!
