### ISSUE TITLE
"Cleanup" doesn't.

### ISSUE THREAD

**Issue by dauith** [yourealwaysbe/forkyz#65]
When I select Cleanup on the puzzle list page, nothing happens.

Too many details, for which I apologise:
- yes, there are completed puzzles in the list (displayed with green circled check marks)
- the same nothing happens whether I set archiving or deleting from Settings
- I tried using both the built-in app storage location and my own download folder -- no difference
- it *is* possible to delete (or archive) by long-pressing individual puzzles and selecting from the top bar

I'm a long-time Shortyz user, but this is my first experience of Forkyz, so it's likely I'm doing something wrong.

- Forkyz version: 38 (I don't see a way in the app to view this, but Android Settings > Apps and F-Droid agree on 38 ... fwiw, installation was via F-Droid)
- Android version: 9
- Device: Samsung Galaxy S8 (which probably limits the Android version)

**Comment by yourealwaysbe** [comment]
Thanks for the bug report. I swipe-to-archive everything rather than cleanup, so i probably broke it at some point and didn't notice. I'll take a look soon.

Let me know if you spot anything else that doesn't work.

**Comment by yourealwaysbe** [comment]
Should be fixed in [Version 39](https://github.com/yourealwaysbe/forkyz/tree/version39) when it's out. It'll probably be a couple of weeks: i'm finishing off some work to support more colourful puzzles that's required a minor overhaul, so would like to let that settle. Then it takes up to a week for FDroid to pick up the changes.

I broke it by only looking for puzzles to clean if the age is assigned to something other than "never" in the settings, forgetting that completed puzzles should be cleared regardless of age.

**Comment by yourealwaysbe** [comment]
> * Forkyz version: 38 (I don't see a way in the app to view this...)

From Version 39, the changelog up to the current version [will be in the release notes](https://github.com/yourealwaysbe/forkyz/commit/352a3c7c3477775be3624b7461e96de8b2c410ea) under settings :)

The current plan is to release at the weekend unless i spot any major issues.

**Comment by dauith** [comment]
Just agreeing that the issue is fixed, and saying Thank You -- Cleanup works, and having the release notes in Settings > About Forkyz is quite nice.

(F-Droid sure was slow about picking up Version 39! I'm going to blame all my lateness in responding on that ;)

**Comment by yourealwaysbe** [comment]
> Just agreeing that the issue is fixed, and saying Thank You -- Cleanup works, and having the release notes in Settings > About Forkyz is quite nice.

Great, thanks for confirming. Your post also prompted me to put in the release notes :)

> (F-Droid sure was slow about picking up Version 39! I'm going to blame all my lateness in responding on that ;)

Yeah -- i think one of their build cycles went wrong, and the backlog took a long time to clear.
