### ISSUE TITLE
Solutions with numbers?

### ISSUE THREAD

**Issue by ryspace** [yourealwaysbe/forkyz#68]
So I was doing today's (3/26/23) Washington Post crossword using Forkys, and there are several clues that have actual numbers in the solutions. As far as I'm aware, there doesn't seem to be a way to type numbers in the app. Is this a feature that exists in the app and I'm just missing?

**Comment by ryspace** [comment]
Okay I found it - Menu > Insert Special

**Comment by yourealwaysbe** [comment]
If you use the native keyboard option, you can also enter numbers from there. (And if the native keyboard doesn't work, let me know -- different keyboards behave differently.)
