### ISSUE TITLE
Lock or display the correct words

### ISSUE THREAD

**Issue by hugleo** [yourealwaysbe/forkyz#69]
Lock or highlight to a slightly different color a correct word.

Or for example, in the list of clues check for error and draw a horizontal line on the words already guessed correctly.

![08-ClueListGrid](https://user-images.githubusercontent.com/4573505/233794887-d940da1c-1a52-47fe-a52a-60541fa93401.png)

**Comment by yourealwaysbe** [comment]
I tried fitting this in with the show errors options. As well as grid, and cursor, i added "clue". The idea is that it highlights a complete clue entry if it contains an error somewhere. If you fill it in and it doesn't highlight, then you got it right (or the puzzle doesn't have the solutions to check against).
