### ISSUE TITLE
Missing system_daynight_mode drawable 

### ISSUE THREAD

**Issue by mooomooo** [yourealwaysbe/forkyz#9]
https://github.com/yourealwaysbe/forkyz/blob/a70f514307439a0f5582fd093da8f9a1e0bc9449/app/src/main/java/app/crossword/yourealwaysbe/BrowseActivity.java#L228

```
error: cannot find symbol
        case SYSTEM: return R.drawable.system_daynight_mode;
                                      ^
  symbol:   variable system_daynight_mode
  location: class drawable
```

**Comment by yourealwaysbe** [comment]
Oops, i should've learned not to make these mistakes by now. Thanks.
